### ISSUE TITLE
Does this query execute too slowly?

### ISSUE THREAD

**Issue by richardcherron** [wharton/wrds#2]
I usually use WRDS's web interface and this query is much slower than I expect. I am not sure if my expectations are wrong or if there is some setting to tweak in `wrds.sql()`.

I query for all dividend announcements with `DISTCD=1232` (quarterly cash dividends) after January 1, 1995. I also want `SHROUT` so I inner join the `DSF` table. This takes nine minutes on my Windows 8.1 laptop with Acaconda's most recent version of Python 2.7. 

Here is the query.

```
select b.PERMNO, b.DCLRDT, b.DIVAMT, a.SHROUT 
from CRSP.DSF a inner join 
(select PERMNO, DCLRDT, DIVAMT from CRSP.DSEDIST 
where DISTCD=1232 & DCLRDT>='01jan1995'd) b 
on a.PERMNO=b.PERMNO and a.DATE=b.DCLRDT 
order by b.PERMNO, b.DCLRDT
```

FWIW, I query from a .py script wrapped in a .ado script (Stata program). But I take the query time from either side of `wrds.sql()` so I don't think this is the problem. I will attach a screen grab and paste my .py script.

Please let me know what other information I can provide.

![wrds](https://cloud.githubusercontent.com/assets/2307622/16995659/8bf9401a-4e7b-11e6-946e-95db896437c6.PNG)

```
# https://wrds-web.wharton.upenn.edu/wrds/support/Accessing%20and%20Manipulating%20the%20Data/_004Python%20Programming/_001Using%20Python%20with%20WRDS.cfmimport wrds
# https://github.com/wharton/wrds
import pandas
import sys
import time
import wrds

# parse arguments
query = sys.argv[1]
froot = sys.argv[2]
csv = sys.argv[3]

# execute query       
print "Query: %s" % query
print "Output file root: %s" % froot
print "Querying..."
t0 = time.time()
result = wrds.sql(call=query, connection=wrds.CONN)
t1 = time.time()
print "Time to execute query: %s" % format(t1-t0, '.1f')

# preview output 
print "Output preview:"
print(result.head())

# write to file
if (csv == "csv"): 
    print "Saving as %s.csv" % froot
    result.to_csv(froot+".csv", index=False)
    print "Saved as %s.csv" % froot
if (csv == ""): 
    print "Trying to save as %s.dta" % froot
    try:
        result.to_stata(froot+".dta", write_index=False)
    except:
        print "Error saving as %s.dta, falling back to %s.csv" % (froot, froot)
        result.to_csv(froot+".csv", index=False)
        print "Saved as %s.csv" % froot

# pause before closing window
raw_input("Press enter to return to Stata")

```

**Comment by cohenmw** [comment]
A couple thoughts. The indexes on dsedist are on permno and exdt.  Can you sub exdt for dclrdt?  Try adding a where clause on a.date to limit the bigger table.  Last suggestion is to try a regular join instead of the subquery.

**Comment by richardcherron** [comment]
Thanks for getting back to me quickly! I will try these and post an update. I am glad to hear that it is operator error (that can be resolved) not a limitation.

Is there a way to tell what are the indexes for each table. I generally look at WRDS pages like [this](https://wrds-web.wharton.upenn.edu/wrds/tools/variable.cfm?library_id=137&file_id=67061) to find table contents.

**Comment by richardcherron** [comment]
If I match on `EXDT` and eliminate the sub-query, then I get a little faster (around 8 minutes).
![wrds](https://cloud.githubusercontent.com/assets/2307622/17038160/5a129d70-4f62-11e6-8e8d-d7451cf530fb.PNG)

**Comment by joedougherty** [comment]
You can determine which fields on a given dataset are indexed by querying the **dictionary.columns** table.

For example, to find out which fields on **crsp.dsf** are indexes, you can run:

`query = """select name, idxusage from dictionary.columns where libname="CRSP" and memname="DSF" and idxusage <> '';"""`
`df = wrds.sql(query)`

This will return a dataframe containing the names of the fields that are indexes as well as the type of index.

**Note**: Both the libname and memname must be capitalized in the select query.

**Comment by qiaoqiaozhu** [comment]
Does this support being run in IPython notebook? Thanks.
