### ISSUE TITLE
Function sql doesn't work because of syntax error

### ISSUE THREAD

**Issue by whoopnip** [wharton/wrds#3]
In the sql function, CONN is passed in as the parameter connection, but this is done while the value of CONN is None. When CONN is updated at the end of the file, it is not reflected in the sql function. Therefore connections don't work.

This can be fixed by removing the connection=CONN parameter and just referencing CONN directly in the function. 

Here's an example of the problem:

    a = 5

    def b(c=a):  #this is what is implemented now
        return c + 1
    
    def d(): #this is how it should be implemented
        return a + 1

    a = 10
    
    b() 
    >> 6 #not updated
    d() 
    >> 11 #updated

**Comment by joedougherty** [comment]
It looks like the GitHub repository was out-of-date with the version of the module that lives on PyPI [https://pypi.python.org/pypi/wrds/0.0.5]

I've now updated the repository which ought to fix this issue.

Thanks!

**Comment by whoopnip** [comment]
I thought the version on PyPI was older. I ended up using the repo version because the PyPI version does not work on Windows. The repo version before checked for the user's operating system, and then splits the classpaths on a semicolon if it's Windows and a colon otherwise. 

Windows paths are of the format C:\etc, so if you split on a colon then it doesn't work properly.
