### ISSUE TITLE
Breaking changes with JayDeBeApi 1.0.0

### ISSUE THREAD

**Issue by dhalik** [wharton/wrds#4]
It appears JayDeBeApi 1.0.0 was just released, and when I tried to use the wrds package I encountered vague errors related to an overloaded method being missing.

```
overloaded methods native/common/jp_method.cpp:117
```

My solution to this was to use JayDeBeApi 0.2.0. It might be prudent to either peg this packages dependency to 0.2.0 or to look into JayDeBeApi 1.0.0 change set.

**Comment by joedougherty** [comment]
Thanks for the note! I've pinned the project to version 0.2.0 of jaydebeapi for the time being.
