### ISSUE TITLE
Why: "credentials found could not be used to authenticate"?

### ISSUE THREAD

**Issue by blucap** [wharton/wrds#6]
I am getting this error when trying to run WRDS from Python 2.7 using my local linux machine : "The credentials found in /home/tenspeed/.wrdsauthrc could not be used to authenticate."

However, with the same credentials on the WRDS-cloud ssh terminal, I **can** run Python interactively:
```
[credentials]
username=tenspeed
password={SAS002}GARBLEDABZEDEFGHIJYHTGTFRDEDEWSEDRFTGYHUJKIOLP
```
Following the instructions here, on my local machine, I added to the .wrdsauthrc file the line:
 
`CLASSPATH=/home/tenspeed/Downloads/SAS-JDBC-Drivers/sas.core.jar:/home/tenspeed/Downloads/SAS-JDBC-Drivers/sas.intrnet.javatools.jar`

Any suggestions?

**Comment by joedougherty** [comment]
@blucap Thanks for writing. Can you confirm that the *.jar files specified in **classpath** definitely exist in those locations on the file system?

**Comment by blucap** [comment]
Solved, I installed **jpype**

`conda install -c conda-forge jpype1=0.6.2`

I also ensured that JAVA_HOME was set in the environment, see [How to set JAVA_HOME for Java](https://askubuntu.com/questions/175514/how-to-set-java-home-for-javal) - though I suspect missing **jpype** was the main culprit.

**Comment by joedougherty** [comment]
@blucap Great to hear :) Best of luck with your research.

**Comment by joedougherty** [comment]
I've added **jpype** to the install_requires in setup.py. This ought to install the package if necessary. 

https://github.com/wharton/wrds/commit/c3768ed74fa8df2a25ba0ecd49c62360159aa1bb
