### ISSUE TITLE
can't pick up the pgpass.conf file

### ISSUE THREAD

**Issue by empenguinxh** [wharton/wrds#7]
I followed the post [Python Programming with WRDS](https://wrds-www.wharton.upenn.edu/pages/support/accessing-and-manipulating-the-data/python-programming-wrds/#jupyter-notebooks-python-from-your-workstation) and set up the `pgpass.conf` file on my laptop. However, command `db = wrds.Connection()` still asked me to enter username and password.

I experimented with the following code.
```
import psycopg2
conn = psycopg2.connect(dbname='wrds', 
                        user='my_username', 
                        host='wrds-pgdata.wharton.upenn.edu', 
                        port=9737)
```
The above code successfully established a connection, which means psycopg2 managed to extract the password stored in `pgpass.conf`. However, if I comment out `user='my_username'`, then the code will raise an exception "fe_sendauth: no password supplied".

Then I experimented with the following code.
```
import sqlalchemy as sa
engine = sa.create_engine('postgresql://wrds-pgdata.wharton.upenn.edu:9737/wrds', 
                          connect_args={'sslmode': 'require', 'user':'my_username'})
engine.connect()
```
Again, the code successfully established a connection. But it will fail if the `user` argument is not provided.

So it seems that for a user who uses windows 10 and hasn't installed "postgresql", "psycopg2 2.7.3.1" requires the user to manually provide the username in order to pick up the information stored in pgpass.conf file.

**Comment by hudcap** [comment]
I'm running Windows 10 and see the same results.

If I run ```db = wrds.Connection()```, input my username at the prompt and leave the password blank, it retrieves the password from the pgpass.conf file.

Additionally, ```db = wrds.Connection(wrds_username = 'username')``` works without any prompt.

@empenguinxh, you implied that installing ```postgresql``` would solve this -- do you mean the python package with that name? Because that didn't work for me.

**Comment by metllord** [comment]
The newest version of the WRDS module should fix this issue. You can pass your WRDS login using the wrds_username argument. This will still read the password from your .pgpass file, but will establish the connection with the correct username. 

To upgrade your WRDS module, run `pip install -U wrds`.
