### ISSUE TITLE
.pgpass does not work

### ISSUE THREAD

**Issue by Seung-hyeon** [wharton/wrds#8]
# Problem

Even though I create my **.pgpass** file in my home directory by following all the [manual](https://wrds-www.wharton.upenn.edu/pages/support/wrds-cloud/holding/python-programming-wrds/),
`wrds.Connection()` still ask the ID and PW.

**/home/ysh/.pgpass**
```
wrds-pgdata.wharton.upenn.edu:9737:wrds:#########:#######
```
> **Note** : ######## is my personal ID and PW

**./sample.py**
```python
import wrds
db = wrds.Connection()
```
```console
Enter your WRDS username [ysh]:
```

# What I have done

I create **.pgpass** file using `create_pgpass_file` method, but it did not work.

```python
import wrds
db = wrds.Connection()
db.create_pgpass_file()
```

## Environment info
Operating System: Linux-4.10.0-28-generic-x86_64-with-debian-stretch-sid

Compiler: [GCC 7.2.0]

Package used (python/R/jvm/C++): Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)

**Comment by metllord** [comment]
Hi.
Could you send the output of `ls -l /home/ysh/.pgpass`? The module will ignore the .pgpass file if the permissions are not correct.

**Comment by Seung-hyeon** [comment]
Here it is!

```console
ysh@ysh-desktop:~$ ls -l /home/ysh/.pgpass
-rw------- 1 ysh ysh 60  2월 28 21:22 /home/ysh/.pgpass
```

**Comment by Seung-hyeon** [comment]
Here,
```console
ysh@ysh-desktop:~$ ls -l /home/ysh/.pgpass
-rw------- 1 ysh ysh 60  2월 28 21:22 /home/ysh/.pgpass

```

I already did,
```console
chmod 600 ~/.pgpass
```

**Comment by metllord** [comment]
If your wrds username does not match the username on your computer, you will have to pass in your wrds username to the connection function.

    db = wrds.connection(wrds_username='wrdsusername')

I will work with our documentation team to make sure this is noted in the module documentation.

**Comment by Seung-hyeon** [comment]
Thanks! now it works!
